# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            'Elias Trommer'
tagline:          'Tech Blog'
description:      'doing digital stuff'
url:              https://jadeaffenjaeger.github.io

author:
    name:           'Elias Trommer'

social-network-links:
    github: https://github.com/jadeaffenjaeger
    linkedin: https://www.linkedin.com/in/elias-trommer-58a085138

paginate: 10

plugins:
    - jekyll-feed
    - jekyll-gist
    - jekyll-paginate

# Sidebar link settings
sidebar_home_link:  true
